version: 0.2
# This buildspec is used by aws CodeBuild and publishes this app to ECR
# We already set privileged: true in our linux environment configuration in CDK
# So this makes Docker available for use here

phases:
  install:
    runtime-versions:
      python: 3.x # To be able to use AWS CLI
    commands:
      - echo installing AWS CLI...
      - pip3 install awscli --upgrade
      - aws --version
  pre_build:
    commands:
      - echo setting AWS zone to eu-west-3...
      - aws configure set default.region eu-west-3
  build:
    commands:
      - echo building docker image
      - docker build -t oonainc/jumbo-bop-nodejs .
